---

- name: load virtualhost
  template: src=vhost.conf dest=/etc/apache2/sites-available/{{ project_host }}.conf
  notify: restart apache2

- name: enable virtualhost
  file: src=/etc/apache2/sites-available/{{ project_host }}.conf dest=/etc/apache2/sites-enabled/{{ project_host }}.conf state=link force=yes
  notify: restart apache2
