---

- name: install php5
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=60
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-mcrypt
    - php5-mysql
    - php5-gd

- name: enable module mcrypt
  shell: php5enmod mcrypt
