---

- name: install php5
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=60
  with_items:
    - php-apc
    - php5
    - php5-cli
    - php5-curl
    - php5-intl
    - php5-mcrypt
    - php5-mysql
    - php5-xdebug
