---

- name: add apt repository for php5.6 packages
  apt_repository:
    repo: ppa:ondrej/php5-5.6
    update_cache: true

- name: install php5.6
  apt: name={{ item }} state=latest update_cache=yes cache_valid_time=60
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-mcrypt
    - php5-mysql
    - php5-gd

- name: enable module mcrypt
  shell: php5enmod mcrypt
  notify: restart apache2

- include: composer.yml
