---

- hosts: all
  sudo: yes
  roles:
    - system
    - apache
    - php
    - node
    - mysql
    - cron
    - git

  vars:
    project:
      name: ptn
      dir: ptn
      host: ptn.local
    vagrant:
      user:
        vagrant
    mysql:
      root:
        password: root
      database: ptn
      username: ptn
      password: ptn
    git:
      user:
        name: Hao Chang
        email: yngwie.chang@gmail.com
